travis:
  secure:
    BINSTAR_TOKEN: RSQPYvImPJEJGZWhvr6r/if91GKh/Uqb5wIJaM+QVgxZV9U1QZ5bA0l7DVwlHdlrytubi6LKaFrK8Xfh3cR0+wl+g+EuhhJqThNiJbp0mPCSX/C2ZRuNqJucAj2tx0CerWPldUY/foWn+6JzTABVdihQHhBHaD04ro/qELmSmyQQRkim/DGT3H+O22L39nKgLgdsddFoLb+sqKCSGWJU+O0BSt5PkVGinQuC9Qj60+qx+LLtMmm1fAygRjWR4pJjZB5lDyiU0zPx4wvoy030kn6pZL2aRnyEuLsfyZnZttlt3pMUm+ZEvUS5wVcPlUM0TetKjgB5GtzK1khoQ4jigUphYJjxjqKuHmoZHRGk5zIOIno09vcvA3aZdd4yiE8X/JhZqyOhKDp9lJJBJ5ydqE3PxpJ6jekmlh5tdXcvzUw/lUxIfMcMnYXxyghKZjefMuhcsxCuf8tdt3VAjlFDWhCMKprlxtyy5LaAfCCMGg2bAAwcyVhQN3Je3OMbwWjhrkh5ScnOQRGQXwCE34hv2wwx4B2rv2il+1S7CbZfahL15KP//5WNL4T7WjbdP9TzG9bKoh29Yagy//0Rrdy8f3+OMijIaY39J74nGkmgczMgjI1kcf0FSB9nfkk8mzsYibMgt6/VMxpcbfwJSDAxxubJ3Koyajomvyaz704BqOg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
